#!/bin/bash

cat <<EOF
<HTML><CENTER>
HomeBrew3 Computer Simulator<BR>
Build: $(date)<BR>
<BR>
<IMG SRC="homebrew3-sm.png">
<BR>
Developed by Douglas Miller<BR>
http://github.com/durgadas311/homebrew3.git/<BR>
<BR>
</CENTER></HTML>
EOF
